// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB24pJGzkwzK0F51o1YeizJkWTngxx0FOU',
    appId: '1:916572029339:web:6386f521717d34004b613e',
    messagingSenderId: '916572029339',
    projectId: 'lms-learningmanagementsystem',
    authDomain: 'lms-learningmanagementsystem.firebaseapp.com',
    storageBucket: 'lms-learningmanagementsystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0mEW-IAEB-gLi7yr8ztovJ0DoUqGc4s',
    appId: '1:916572029339:android:b4384d6d544eafec4b613e',
    messagingSenderId: '916572029339',
    projectId: 'lms-learningmanagementsystem',
    storageBucket: 'lms-learningmanagementsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpLLa8qsgOoMGNv2genbwpqLOaDEHNJto',
    appId: '1:916572029339:ios:fd7dd5daf7bbb9ac4b613e',
    messagingSenderId: '916572029339',
    projectId: 'lms-learningmanagementsystem',
    storageBucket: 'lms-learningmanagementsystem.appspot.com',
    iosClientId: '916572029339-p2fmdik5kn5jcnq8h2u7tkuk9ambb170.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpLLa8qsgOoMGNv2genbwpqLOaDEHNJto',
    appId: '1:916572029339:ios:fd7dd5daf7bbb9ac4b613e',
    messagingSenderId: '916572029339',
    projectId: 'lms-learningmanagementsystem',
    storageBucket: 'lms-learningmanagementsystem.appspot.com',
    iosClientId: '916572029339-p2fmdik5kn5jcnq8h2u7tkuk9ambb170.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApplication',
  );
}
